### PR TITLE
Fix for cache overwriting and creating separate file for each launch

### PR DESCRIPTION
**Pull request by darshanhurix**

### CODE REVIEW

**Review by bodhibhurix — APPROVED** [review]
looks good to be merged. 
But we need to think of some process of clearing off the /tmp directory periodically

**Comment by thepdr** [comment]
@darshanhurix , can we review this again?  To me it looks like the original implementation should be reading the contents of the cache (all cached launches) and adding to or updating those launches based on the key and then rewriting the whole structure back to the file.  I don't think we want to try and write a new file for every launch.

**Comment by darshanhurix** [comment]
Hi @thepdr ,

As you said yes it does store and get the details from the cache but during each launch the lti_cache.txt is reset and we tried getting the object its give a blank instance every time on new launch, so if there are simultaneous launches it will wipe out one users launch and hence we get 500 error while pass back.

What we tried 

1. A **teacher A** launches successfully to assignment creation page
2. **Teacher B** also launches the same tool to assignment creation page
3. **Teacher A** saves the assignment and gets 500 error as the lti_cache.txt file has only details of **Teacher B**

The below line depicts that on every new message launch initialization the cache is empty
IMSGlobal\LTI\Cache Object ( [cache:IMSGlobal\LTI\Cache:private] => )

CC : @BECkvalentine @shijo-john @bodhibhurix @BECkvalentine @ebredy @abhishekmhurix

**Comment by darshanhurix** [comment]
@thepdr 

As requested I have pushed the code of memcache to Library which can be forked back to IMSGlobal repo, have pushed my changes will you please have a look at it once and suggest your feedback for the same

CC : @BECkvalentine @ebredy @bodhibhurix

**Comment by thepdr** [comment]
@darshanhurix , I think this looks good, but would it make more sense or be more flexible if we moved the MemCache class into Janus?  If we ever needed to make changes to the MemCache class we wouldn't have to touch the vendor library.  Thoughts?

@BECkvalentine @bodhibhurix @ebredy @bnrath

**Comment by darshanhurix** [comment]
@thepdr , 

By keeping mem cache we are adding one additional feature to the original library which might help other developers, kindly let me know if you want me to move this to janus we can definitely do that

@bnrath @BECkvalentine @ebredy @bodhibhurix

**Review by thepdr — APPROVED** [review]

**Pull request merged**
